syntax = "proto3";

package RobotStaticStatus;

option java_package = "com.mqttclient.protobuf.gen";
option java_outer_classname = "RobotStaticStatusProto";

message RobotStaticStatus {
    optional uint32 connection_state = 1;
    optional uint32 field_state = 2;
    optional uint32 alive_state = 3;
    optional uint32 robot_id = 4;
    optional uint32 robot_type = 5;
    optional uint32 performance_system_shooter = 6;
    optional uint32 performance_system_chassis = 7;
    optional uint32 level = 8;
    optional uint32 max_health = 9;
    optional uint32 max_heat = 10;
    optional float heat_cooldown_rate = 11;
    optional uint32 max_power = 12;
    optional uint32 max_buffer_energy = 13;
    optional uint32 max_chassis_energy = 14;
}